/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bank { 'code' : string, 'name' : string }
export interface BankCategory {
  'category' : string,
  'banks' : Array<Bank>,
  'totalInCategory' : bigint,
}
export interface QRCode { 'bank' : string, 'mobileNumber' : string }
export interface TransactionRecord {
  'transactionType' : TransactionType,
  'rewardAmount' : number,
  'timestamp' : bigint,
  'counterpartyMobile' : string,
  'amount' : number,
}
export type TransactionType = { 'sent' : null } |
  { 'received' : null };
export interface UserProfile {
  'bankAccountNumber' : string,
  'mobileNumber' : string,
  'selectedBank' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllQRCodes' : ActorMethod<[], Array<QRCode>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getBalance' : ActorMethod<[], number>,
  'getBalanceByUser' : ActorMethod<[Principal], number>,
  'getCallerQRCode' : ActorMethod<[], [] | [QRCode]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategorizedBankList' : ActorMethod<[], Array<BankCategory>>,
  'getQRCodeByMobile' : ActorMethod<[string], [] | [QRCode]>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getTransactionHistoryByUser' : ActorMethod<
    [Principal],
    Array<TransactionRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkBankAccount' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMoney' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];