/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QRCode = IDL.Record({
  'bank' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'selectedBank' : IDL.Text,
});
export const Bank = IDL.Record({ 'code' : IDL.Text, 'name' : IDL.Text });
export const BankCategory = IDL.Record({
  'category' : IDL.Text,
  'banks' : IDL.Vec(Bank),
  'totalInCategory' : IDL.Int,
});
export const TransactionType = IDL.Variant({
  'sent' : IDL.Null,
  'received' : IDL.Null,
});
export const TransactionRecord = IDL.Record({
  'transactionType' : TransactionType,
  'rewardAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'counterpartyMobile' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllQRCodes' : IDL.Func([], [IDL.Vec(QRCode)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getBalanceByUser' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getCallerQRCode' : IDL.Func([], [IDL.Opt(QRCode)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorizedBankList' : IDL.Func([], [IDL.Vec(BankCategory)], ['query']),
  'getQRCodeByMobile' : IDL.Func([IDL.Text], [IDL.Opt(QRCode)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getTransactionHistoryByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMoney' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QRCode = IDL.Record({ 'bank' : IDL.Text, 'mobileNumber' : IDL.Text });
  const UserProfile = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'selectedBank' : IDL.Text,
  });
  const Bank = IDL.Record({ 'code' : IDL.Text, 'name' : IDL.Text });
  const BankCategory = IDL.Record({
    'category' : IDL.Text,
    'banks' : IDL.Vec(Bank),
    'totalInCategory' : IDL.Int,
  });
  const TransactionType = IDL.Variant({
    'sent' : IDL.Null,
    'received' : IDL.Null,
  });
  const TransactionRecord = IDL.Record({
    'transactionType' : TransactionType,
    'rewardAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'counterpartyMobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllQRCodes' : IDL.Func([], [IDL.Vec(QRCode)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getBalanceByUser' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getCallerQRCode' : IDL.Func([], [IDL.Opt(QRCode)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorizedBankList' : IDL.Func([], [IDL.Vec(BankCategory)], ['query']),
    'getQRCodeByMobile' : IDL.Func([IDL.Text], [IDL.Opt(QRCode)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getTransactionHistoryByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMoney' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };